"""
Machine-wide discovery of Prompt Studio map sources for the backfill.

Walks the given roots and collects every directory and every .zip whose name
contains "prompt_" (case-insensitive), plus every other .zip found directly in
the given bundle roots (group bundles like [Sandy].zip carry several resources;
the backfill only hashes their entries whose path contains "prompt_").
Matched directories nested inside another matched directory are dropped, since
the parent walk already covers them.

Usage:
    python tools/discover-prompt.py --out tools/backfill-prompt-all.json
"""
import argparse
import json
import os

ROOTS = [
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources",
    "C:/txData/QBCore_77D2E4.base/resources",
    "C:/FXServer_Enhanced",
    "C:/Scripts",
    "C:/temp/mlos",
    "C:/temp/brp",
    "D:/Sandymapdata",
    "D:/!IMPORTANT",
]
BUNDLE_ROOTS = [
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]/[Sandy]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]/[Small]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[promptsandy]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[MRPD]",
]
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".remember", ".claude", "obj", "bin", "cache"}
MAX_DEPTH = 7
NEEDLE = "prompt_"


def discover():
    dirs, zips = [], []
    for root in ROOTS:
        if not os.path.isdir(root):
            print(f"(missing root) {root}")
            continue
        base_depth = root.rstrip("/").count("/")
        for current, subdirs, files in os.walk(root):
            depth = current.replace("\\", "/").count("/") - base_depth
            subdirs[:] = [d for d in subdirs if d.lower() not in SKIP_DIRS]
            matched_here = []
            for d in subdirs:
                if NEEDLE in d.lower():
                    matched_here.append(d)
                    dirs.append(os.path.join(current, d).replace("\\", "/"))
            # do not descend into matched directories (their walk is the backfill's job)
            subdirs[:] = [d for d in subdirs if d not in matched_here]
            if depth >= MAX_DEPTH:
                subdirs[:] = []
            for f in files:
                if f.lower().endswith(".zip") and NEEDLE in f.lower():
                    zips.append(os.path.join(current, f).replace("\\", "/"))
    for root in BUNDLE_ROOTS:
        if not os.path.isdir(root):
            continue
        for f in os.listdir(root):
            p = f"{root}/{f}"
            if f.lower().endswith(".zip") and os.path.isfile(p) and p not in zips:
                zips.append(p)
    return sorted(set(dirs)), sorted(set(zips))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    dirs, zips = discover()
    config = {
        "_comment": "Generated by tools/discover-prompt.py: every folder/zip with prompt_ in the name under the local roots, plus bundle zips filtered to prompt_ entries.",
        "groups": {
            "prompt-catalog": {
                "dirs": dirs,
                "zips": zips,
                "include": [],
                "exclude": [],
                "entry_include": ["*prompt_*"],
            }
        },
    }
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(config, handle, indent=2)
        handle.write("\n")
    print(f"dirs: {len(dirs)}  zips: {len(zips)}  -> {args.out}")
    for d in dirs:
        print("  dir", d)
    for z in zips:
        print("  zip", z)


if __name__ == "__main__":
    main()
