"""
Machine-wide discovery of Prompt Studio map sources for the backfill.

Walks the given roots and collects every directory and every .zip whose name
contains one of NEEDLES (case-insensitive), plus every other .zip found
directly in the given bundle roots (group bundles like [Sandy].zip carry
several resources; the backfill only hashes their entries whose path matches a
needle). Matched directories nested inside another matched directory are
dropped, since the parent walk already covers them.

Usage:
    python tools/discover-prompt.py --out tools/backfill-prompt-all.json
"""
import argparse
import json
import os

# Our own build-machine locations only. Customer packs (their downloaded
# copies under C:/temp) are deliberately not scanned: a copy sitting in a
# customer's pack may carry their edits, and the list must bless our releases,
# not someone's modified copy of one.
ROOTS = [
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources",
    "C:/txData/QBCore_77D2E4.base/resources",
    "C:/FXServer_Enhanced",
    "C:/Scripts",
    "D:/!IMPORTANT",
]
BUNDLE_ROOTS = [
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]/[Sandy]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[prep]/[Small]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[promptsandy]",
    "C:/5m_Server/txData/CFXDefault_F6E3BF.base/resources/[MRPD]",
]
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".remember", ".claude", "obj", "bin", "cache"}
MAX_DEPTH = 7
# Name fragments that mark a resource as ours. "prompt_" covers the Prompt
# Studio catalog; "chuz_" the chuz maps; the Rockford PD entry is the
# fd-compatible edition only (the plain rockford_police_department resource is
# deliberately not listed).
NEEDLES = ["prompt_", "chuz_", "rockford_police_department(fd_compatible)"]
# Mapdata is a merged product of its own and is not listed.
SKIP_NEEDLE = "mapdata"


# Legacy products whose folder name predates the prompt_ convention. Each was
# confirmed by content: its custom-named files carry our prefixes, or it is a
# named edition of one of our maps. Names are matched exactly (folders), and a
# zip of the same name is taken too.
EXTRA_RESOURCES = [
    "rockford_police_department",
    "LSFD",
    "Los_Santos_City_Hall",
    "city_hall_lawn_christmas",
    "city_hall_lawn_christmas_emptied",
    "cfx_Christmas_Fair_Sandy_Shores",
    "halloween_stuff",
    "noose_prompt",
    "prison_tower",
    "Prompt-ATLAS-MAP",
    "map-prompt",
    "cfx_vfd_ext_old",
    "cfx_vfd_dfgdfg",
    "cfx_vfd_sdf",
]
EXTRA_LOWER = {name.lower() for name in EXTRA_RESOURCES}


def is_ours(name):
    lower = name.lower()
    if lower in EXTRA_LOWER or os.path.splitext(lower)[0] in EXTRA_LOWER:
        return True
    return any(needle in lower for needle in NEEDLES)


def is_merged_pack(name):
    """Merged compatibility products, never listed: mapdata by name, and the
    per-customer combination packs, which are named after the maps they were
    built for ("GN-Clinic+Burgershott+...+Prompt_Sheriff"). Their content is
    merged output, not a release of ours."""
    lower = name.lower()
    return SKIP_NEEDLE in lower or "+" in name


def discover():
    dirs, zips = [], []
    for root in ROOTS:
        if not os.path.isdir(root):
            print(f"(missing root) {root}")
            continue
        base_depth = root.rstrip("/").count("/")
        for current, subdirs, files in os.walk(root):
            depth = current.replace("\\", "/").count("/") - base_depth
            subdirs[:] = [d for d in subdirs if d.lower() not in SKIP_DIRS]
            matched_here = []
            for d in subdirs:
                if is_ours(d) and not is_merged_pack(d):
                    matched_here.append(d)
                    dirs.append(os.path.join(current, d).replace("\\", "/"))
            # do not descend into matched directories (their walk is the backfill's job)
            subdirs[:] = [d for d in subdirs if d not in matched_here]
            if depth >= MAX_DEPTH:
                subdirs[:] = []
            for f in files:
                if f.lower().endswith(".zip") and is_ours(f) and not is_merged_pack(f):
                    zips.append(os.path.join(current, f).replace("\\", "/"))
    for root in BUNDLE_ROOTS:
        if not os.path.isdir(root):
            continue
        for f in os.listdir(root):
            p = f"{root}/{f}"
            if f.lower().endswith(".zip") and os.path.isfile(p) and p not in zips:
                zips.append(p)
    return sorted(set(dirs)), sorted(set(zips))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    dirs, zips = discover()
    config = {
        "_comment": "Generated by tools/discover-prompt.py: every folder/zip whose name carries one of the discovery needles (prompt_, chuz_, rockford fd-compatible) under the local roots, plus bundle zips filtered to those same entries.",
        "groups": {
            "prompt-catalog": {
                "dirs": dirs,
                "zips": zips,
                "include": [],
                "exclude": [],
                "entry_include": [f"*{needle}*" for needle in NEEDLES],
            }
        },
    }
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(config, handle, indent=2)
        handle.write("\n")
    print(f"dirs: {len(dirs)}  zips: {len(zips)}  -> {args.out}")
    for d in dirs:
        print("  dir", d)
    for z in zips:
        print("  zip", z)


if __name__ == "__main__":
    main()
